### ISSUE TITLE
Errors in houdini console

### ISSUE THREAD

**Issue by krasnovpro** [instance-id/Searcher#1]
```
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\searcher.py:840: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (key[0] is not '+'):
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\searcher.py:924: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\database.py:202: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\database.py:212: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\database.py:220: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\searchersetup.py:233: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\searchersetup.py:242: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
c:\Users/user/Documents/houdini_addons/Searcher/python3.9libs\searcher\searchersetup.py:251: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hkcheck) is 0:
```

Houdini 19.5

**Comment by instance-id** [comment]
My apologies, I didn't get a notification that there was a post. Are you still using 19.5, or 20 now? I just updated for v20 compatibility, but only tested on linux so far. I need to get another windows VM going to test it on.

**Comment by krasnovpro** [comment]
I'm still on 19.5.

**Comment by instance-id** [comment]
Do you have any additional details you can share that might help me to reproduce this? Ex. What specific version did you try it on (also, windows 10, or 11)? Were you using the standard install, or the py37 install? Did this happen upon first opening Houdini, or when trying to pull up the search window? 

I will try to get setup with the same so that I can try and see it in action on my end.

--- Edit: Those look like warning message that started appearing in a specific version of python. Warnings should not interfere with operation, I don't believe. Though, if that were the case, you probably would not have needed to make a post here. Is it causing an error window to show up or something along those lines?
